config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :books do
    resources :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  root 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments
  
  validates :title, presence: true
	validates :body, presence: true
	validates :body, presence: true, length: { maximum: 200 }
	
def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites
  has_many :favorited_books, through: :favorites, source: :book
  has_many :book_comments

  attachment :profile_image
  validates :name, presence: true, length: {minimum: 2,maximum: 20}
  validates :name, uniqueness:true, length:{ in: 2..20 }
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!,except:[:top,:about]
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:password])
  end
  
  def  after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  def  after_sign_up_path_for(resource)
    user_path(current_user)
  end
  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
 
before_action :authenticate_user!

  def create
    book = Book.find(params[:book_id])
    @comment = BookComment.new(book_comment_params)
    @comment.user_id = current_user.id   #@comment子供の、親のid(user_id)を知りたい
    @comment.book_id = book.id
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    comment = BookComment.find(params[:id])
    comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:content)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
 before_action:correct,only:[:edit]
 
  def index
    @new_book = Book.new
    @books = Book.all
    @user = current_user
    @favorite = Favorite.new
  end
  
  def create
     @book = Book.new(book_params)
     @book.user_id = current_user.id
    if @book.save
     flash[:notice] = "You have creatad book successfully."
     redirect_to book_path(@book)
    else
      flash[:notice] = "can't be blank"
      @user = User.find(current_user.id)
      @books = Book.all.order(create_at: :desc)
      render "index"
    end
  end
  
  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = User.find_by(id: @book.user_id)
    @favorite = Favorite.new
    @comment = BookComment.new
    @comments = @book.book_comments
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
     flash[:notice]="successfully updated"
     redirect_to book_path(@book)
    else
      flash[:notice]="updating error"
      render "edit"
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  def correct
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
  
 private
  def book_params
    params.require(:book).permit(:title, :body).merge(user_id: current_user.id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		@favorite= current_user.favorites.create(book_id: params[:book_id])
		@favorite.save
		redirect_back(fallback_location: root_path)
	end
	
	def destroy
		@favorite = Favorite.find_by(book_id: params[:book_id], user_id: current_user.id)
		@favorite.destroy
		redirect_back(fallback_location: root_path)
	end
	  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
 before_action:correct,only: [:edit]
  
  def index
    @users = User.all
    @user =current_user
    @book = Book.new
  end
  

  def show
    @user = User.find(params[:id])
    @user_books = @user.books
    @book = Book.new
  end

  def edit
   
  end
  
  def update
    @book = Book.new
    @users = User.all
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success]="successfully updated"
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end
  
  def correct
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body).merge(user_id: current_user.id)
  end
  
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.html.erb
<h1>BookComments#create</h1>
<p>Find me in app/views/book_comments/create.html.erb</p>

app/views/book_comments/destroy.html.erb
<h1>BookComments#destroy</h1>
<p>Find me in app/views/book_comments/destroy.html.erb</p>

app/views/books/_new_book.html.erb
<h4>New book</h4>
      <%= form_with model:book,local:true do |f| %>
        <p>Title</p>
        <%= f.text_field :title,class:"w-100"%>
        <p class="mt-2">Opinion</p>
        <%= f.text_area :body,class:"w-100 " %>
        <p class="mt-2"><%= f.submit "Create Book",class:"text-white bg-success rounded border-0 pt-1 pb-1" %></p>
      <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <h4 class="mt-3">Editing Book</h4>
      <%= form_with model:@book,local:true do |f| %>
        <p>Title</p>
        <%= f.text_field :title,class:"w-100" %>
        <p class="mt-2">Opinion</p>
        <%= f.text_area :body,class:"w-100" %>
        <p class="mt-2"><%= f.submit "Update Book" %></p>
      <% end %>
      <%= link_to "Show",book_path(@book) %> | <%= link_to "Back",books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%# 新規投稿・投稿更新時　サクセスメッセージ %>
      <% if flash[:success] %>
        <%= flash[:success] %>
      <% end %>
      <%# プロフィール編集 %>
       <%= render 'users/user_info' %>
      <%# 新規投稿 %>
      <%= render 'books/new_book',book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
        <h2 class="mt-4">Books</h2>
        <table class="table table-hover table-inverse">
         <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
           </tr>
          </thead>
          <% @books.each do |book| %>
            <tr class="border-top border-bottom">
              <td class="pt-2 pb-2"><%= link_to attachment_image_tag(book.user, :profile_image, size: "60x60" , fallback: "no_image.jpg"),user_path(book.user) %></td>
              <td><%=link_to book.title,book_path(book) %></td>
              <td><%= book.body %></td>
              <!--いいね機能-->
            　<% if book.favorited_by?(current_user) %>
                <td>
                  <%= link_to book_favorite_path(book.id,book.favorites), method: :delete do %>
                    <i class="fas fa-heart"></i>
                    <%= book.favorites.count %>
                  <% end %>
               </td>
              <% else %>
                <td>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <i class="far fa-heart"></i>
                    <%= book.favorites.count %>
                  <% end %>
                </td>
              <% end %>
              <td>コメント数:<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </table>
      </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
   <div class="col-md-3">
      <!--プロフィール編集-->
     <h4 class="mt-4">User info</h4>
      <%= attachment_image_tag @book.user, :profile_image, size: "60x60" , fallback: "no_image.jpg"%>
       <p class="border-top border-bottom pt-2 pb-2">name<%= @book.user.name %></p>
      <p>introduction <%= @book.user.introduction %></p>
      <button class="btn btn-outline-secondary btn-block fas fa-user-cog">
        <%= link_to edit_user_path(@book.user) do %>
    　     <i class="fas fa-user-cog text-secondary"></i>
    　　　<% end %>
　　　</button>
　　　 <%# 新規投稿 %>
      <%= render 'books/new_book',book: @new_book %>
    </div>
   <div class="col-md-8 offset-md-1">
      <%# 投稿詳細 %>
      <h4 class="border-bottom mt-4">Book detail</h4>
      <p><%= link_to attachment_image_tag(@user, :profile_image, size: "60x60" , fallback: "no_image.jpg"),user_path(@user.id) %></p>
      <%= link_to "#{@user.name}",user_path(@user.id) %>
      <%= link_to "#{@book.title}",books_path(@book) %>
      <%= @book.body %>
    　<!--コメント数、編集・削除機能-->
      <td>コメント数:<%= @book.book_comments.count %></td>
					<% if @book.user.id == current_user.id %>
						<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
						<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
		</table>
	　<!--コメント一覧-->
		<table>
			<% @comments.each do |comment| %>
				<tr>
					<td>
						<%= link_to user_path(comment.user) do %>
							<%= attachment_image_tag(comment.user, :profile_image, :fill, 100, 100, fallback: "no_image_mini.jpg") %><br>
							<%= comment.user.name %>
						<% end %>
					</td>
					<td>
						<%= comment.content %>
					</td>
					<% if comment.user_id == current_user.id %>
						<td><%= link_to "Destroy", book_book_comment_path(@book.id, comment.id), method: :delete, class:"btn btn-danger" %></td>
					<% end %>
				</tr>
			<% end %>
		</table>
		<table>
			<tr> 
				<%= form_with(model:[@book,@comment], local: true) do |f| %>
					<%= f.text_area :content, class: "col-xs-8" %>
					<%= f.submit "送信" %>
				<% end %>
			</tr>
		</table>
    </div>
    
  </div>
</div>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
 </div>
</main>

app/views/homes/top.html.erb
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/e1408edfcc.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <header>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/"><span>Bookers</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
         </button>
     <div class="collapse navbar-collapse" id="navbarNavDropdown">
       <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
              <!-- login時header -->
              
              <li class="">
                <%= link_to 'Home', user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
              </li>
              <li class="">
                <!-- users/index = users_path -->
                <%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %>
              </li>
              <!-- books/index = _path -->
              <li class="">
                <%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %>
              </li>
              <li class="">
                <%= link_to "Logout", destroy_user_session_path, class: "fas fa-sign-out-alt nav-link text-light", method: :delete %>
              </li>
            <% else %>
              <!-- logout時header -->
              <!-- top -->
              <li class="bi bi-house-door">
                <%= link_to 'Home', root_path, class: "fas fa-home nav-link text-light" %>
              </li>
              <!-- about -->
              <li class="">
                <%= link_to "About", about_path, class: "fas fa-link nav-link text-light" %>
              </li>
              <!--signup-->
              <li class="">
                <%= link_to "Sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
              </li>
              <!--login-->
              <li class="">
                <%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
 </nav>

    </header>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
         <div class="mx-auto">
    		  <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_user_info.html.erb
<h4 class="mt-4">User info</h4>
      <%= attachment_image_tag @user, :profile_image, size: "60x60" , fallback: "no_image.jpg"%>
       <p class="border-top border-bottom pt-2 pb-2">name<%= @user.name %></p>
      <p>introduction <%= @user.introduction %></p>
      
      <button class="btn btn-outline-secondary btn-block fas fa-user-cog">
        <%= link_to edit_user_path(@user) do %>
    　     <i class="fas fa-user-cog text-secondary"></i>
    　　　<% end %>
　　　</button>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <% @user.errors.full_messages.each do |user| %>
    <%= user %>
  <% end %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <h4 class="mt-3">User info</h4>
      <%= form_with model:@user,local:true do |f| %>
        <p>Name</p>
        <%= f.text_field :name,class:"w-100" %>
        <p class="mt-2">image</p>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        <p class="mt-2">introduction</p>
        <%= f.text_area :introduction,class:"w-100" %>
        <p class="mt-2"><button><%= f.submit "Update User" %></button></p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
 <div class="row"> 
  <div class="col-md-3">
      <%# 新規投稿・投稿更新時　サクセスメッセージ %>
      <% if flash[:success] %>
        <%= flash[:success] %>
      <% end %>
      <%# プロフィール編集 %>
      <h4 class="mt-4">User info</h4>
      <%= attachment_image_tag @user, :profile_image, size: "60x60" , fallback: "no_image.jpg"%>
       <p class="border-top border-bottom pt-2 pb-2">name<%= @user.name %></p>
      <p>introduction <%= @user.introduction %></p>
      
      <button class="btn btn-outline-secondary btn-block fas fa-user-cog">
        <%= link_to edit_user_path(@user) do %>
    　     <i class="fas fa-user-cog text-secondary"></i>
    　　　<% end %>
    　　　</button>
    
      <%# 新規投稿 %>
      <h4>New book</h4>
      <%= form_with model:@book,local:true do |f| %>
         <p>Title</p>
        <%= f.text_field :title,class:"w-100"%>
        <p class="mt-2">Opinion</p>
        <%= f.text_area :body,class:"w-100 " %>
        <p class="mt-2"><%= f.submit "Create Book",class:"text-white bg-success rounded border-0 pt-1 pb-1" %></p>
      <% end %>
  </div>
  <div class="col-md-8 offset-md-1">
   <h2 class="mt-2">Users</h2>
        <table class="w-100">
          <tr class="border-top border-bottom">
            <td class="pt-2 pb-2">image</td>
            <td>name</td>
          </tr>
          <% @users.each do |user| %>
            <tr class="border-top border-bottom">
              <td class="pt-2 pb-2"><%= attachment_image_tag user, :profile_image, size: "60x60" , fallback: "no_image.jpg"%></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show",user_path(user) %></td>
            </tr>
          <% end %>
        </table>
 </div>
 </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
   <div class="col-md-3">
      <%# 新規投稿・投稿更新時　サクセスメッセージ %>
      <% if flash[:success] %>
        <%= flash[:success] %>
      <% end %>
      <%# プロフィール編集 %>
      <h4 class="mt-4">User info</h4>
      <%= attachment_image_tag @user, :profile_image, size: "60x60" , fallback: "no_image.jpg"%>
       <p class="border-top border-bottom pt-2 pb-2">name<%= @user.name %></p>
      <p>introduction <%= @user.introduction %></p>
      <button class="btn btn-outline-secondary btn-block fas fa-user-cog">
        <%= link_to edit_user_path(@user) do %>
    　     <i class="fas fa-user-cog text-secondary"></i>
    　　　<% end %>
    　</button>
      <%# 新規投稿 %>
      <h4>New book</h4>
      <%= form_with model:@book,local:true do |f| %>
         <p>Title</p>
        <%= f.text_field :title,class:"w-100"%>
        <p class="mt-2">Opinion</p>
        <%= f.text_area :body,class:"w-100 " %>
        <p class="mt-2"><%= f.submit "Create Book",class:"text-white bg-success rounded border-0 pt-1 pb-1" %></p>
      <% end %>
  　</div>
   <div class="col-md-8 offset-md-1">
          <%# ユーザー別投稿一覧 %>
          <h2 class="mt-4">Books</h2>
           <table class="w-100">
            <tr class="w-100 border-top border-bottom">
              <td class="pt-2 pb-2">　</td>
              <td>Title</td>  
              <td>Opinion</td>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <% @user_books.each do |book| %>
            <tr>
              <td><p><%= link_to attachment_image_tag(book.user, :profile_image, size: "60x60" , fallback: "no_image.jpg"),user_path(book.user) %></p>
              </td>
              <td><%= link_to "#{book.title}",book_path(book) %></td>
              <td><%= book.body %></td>
              <td>コメント:<%= book.book_comments.count %></td>
            </tr>
            <% end %>
          </table>
    </div>
  </div>
</div>